name: ci

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      # To avoid terminating all jobs when one job fails.
      fail-fast: false
      matrix:
        include:
          # ---------------------------------------------------------------------------------------
          # CentOS 7
          # ---------------------------------------------------------------------------------------
          - name: centos7-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48

          # Clang 15
          - name: centos7-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48

          - name: centos7-x86_64-clang15-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48

          # ---------------------------------------------------------------------------------------
          # Ubuntu 20.04
          # ---------------------------------------------------------------------------------------
          - name: ubuntu2004-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2004_x86_64:v2022-10-13T18_10_48

          # ---------------------------------------------------------------------------------------
          # Ubuntu 22.04
          # ---------------------------------------------------------------------------------------

          - name: ubuntu2204-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2204_x86_64:v2022-10-13T18_10_50

          - name: ubuntu2204-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2204_x86_64:v2022-10-13T18_10_50

          # ---------------------------------------------------------------------------------------
          # AlmaLinux 8
          # ---------------------------------------------------------------------------------------
          - name: almalinux8-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49

          # Clang/LLVM 15
          - name: almalinux8-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49

          - name: almalinux8-x86_64-clang15-linuxbrew
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49

          - name: almalinux8-x86_64-clang15-linuxbrew-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # We need to fetch all history because we are cloning the checkout directory further
          # in test code.
          fetch-depth: 0

      - name: Build
        run: |
          ./.github/workflows/linux_build.sh
        env:
          YB_DOCKER_IMAGE: ${{ matrix.docker_image }}